# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Poly dist3 C
#'
#' @param objsp1 object from class \code{SpatialPolygons}
#' @param objsp2 object from class \code{SpatialPolygons}
#'
#' @return an object from class \code{SpatialPolygons} randomly translated
#'
PolyDist <- function(objsp1, objsp2) {
    .Call('_tpsa_PolyDist', PACKAGE = 'tpsa', objsp1, objsp2)
}

PolyInter <- function(objsp1, objsp2) {
    .Call('_tpsa_PolyInter', PACKAGE = 'tpsa', objsp1, objsp2)
}

#' Polygons that touch a bbox
#'
#' @param x a \code{SpatialPolygon}
#' @param bbox a \code{numeric matrix}
#'
#' @export
#'
poly_touch <- function(x, bbox) {
    .Call('_tpsa_poly_touch', PACKAGE = 'tpsa', x, bbox)
}

#' Polygons' Random Shift - 2
#'
#' @param objsp object from class \code{SpatialPolygons}
#' @param bbox_max Boundary box from class \code{matrix}
#'
#' @return an object from class \code{SpatialPolygons} randomly translated
#'
poly_rf2 <- function(objsp, bbox_max) {
    .Call('_tpsa_poly_rf2', PACKAGE = 'tpsa', objsp, bbox_max)
}

#' Auxiliar function
#'
#' @param obj_sp a spatial object
#' @param obj_sp2 a spatial object
#' @param obj_sp3 a spatial object
#' @param obj_sp4 a spatial object
#' @param n_poly an integer
#' @param range_x a numeric
#' @param range_y a numeric
#'
shift_aux <- function(obj_sp, obj_sp2, obj_sp3, obj_sp4, n_poly, range_x, range_y) {
    .Call('_tpsa_shift_aux', PACKAGE = 'tpsa', obj_sp, obj_sp2, obj_sp3, obj_sp4, n_poly, range_x, range_y)
}

#' Create copies of a set of polygons
#'
#' @param obj_sp object from class \code{SpatialPolygons}
#' @param bbox_tot Boundary box from class \code{matrix}
#'
#' @description Auxiliar function.
#'
#' @importFrom stats runif
#' @return an object from class \code{SpatialPolygons}
#'
poly_shift <- function(obj_sp, bbox_tot) {
    .Call('_tpsa_poly_shift', PACKAGE = 'tpsa', obj_sp, bbox_tot)
}

#' Toroidal edge correction
#'
#' @param objsp a \code{SpatialPolygon}
#' @param bbox_tot a \code{numeric matrix}
#'
#' @export
#'
torus_corr <- function(objsp, bbox_tot) {
    .Call('_tpsa_torus_corr', PACKAGE = 'tpsa', objsp, bbox_tot)
}

