# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Auxiliar function
#'
#' @param obj_sp a spatial object
#' @param obj_sp2 a spatial object
#' @param obj_sp3 a spatial object
#' @param obj_sp4 a spatial object
#' @param n_poly an integer
#' @param range_x a numeric
#' @param range_y a numeric
#'
shift_aux <- function(obj_sp, obj_sp2, obj_sp3, obj_sp4, n_poly, range_x, range_y) {
    .Call('_pat_shift_aux', PACKAGE = 'pat', obj_sp, obj_sp2, obj_sp3, obj_sp4, n_poly, range_x, range_y)
}

